import random

#Lyrics from the top 100 songs of 2018
billboardtop = ["I've been me since Scarlett Road",
         "I never knew you were the someone waiting for me",
          "We got nothing but time",
          "If it cost a million, that's me",
          "I feel just like a rockstar",
          "Can't really trust nobody with all this jewelry on you",
          "You gotta believe me when I tell you",
          "So why don't you just meet me in the middle?",
          "Say you'll never ever leave",
          "Maybe it's 6:45",
          "How can I explain myself?",
          "Easier said than done",
          "Life, it goes on, what can you do?",
          "You know it",
          "Can't control my anxiety",
          "Talkin' in my sleep at night",
          "Who am I? Someone that's afraid to let go",
          "Let go of the wheel",
          "Underneath the sunrise",
          "Right now, I'm in a state of mind",
          "This feel incredible",
          "I was dreaming of bigger things",
          "Look alive",
          "My reputation's never been worse",
          "I just took what they gave me",
          "I've told you one, two, three, four, five, six thousand times",
          "I'm gonna walk away",
          "And I got the fire",
          "I wish that I could say I'm proud",
          "Concentrate",
          "Colorful hair, don't care",
          "I can hang with anybody",
          "I'm a rebel just for kicks, now",
          "Face all your fears",
          "Burning through the hours talking",
          "Lately our conversations end like it's the last goodbye",
          "Everybody hoping they could be the one",
          "So do not test me",
          "You said it",
          "It's all the same",
          "Every single word builds up to this moment",
          "Cut the lights",
          "Take my shoes and walk a mile",
          "No wedding ring",
          "I'd never lie",
          "Sometimes I feel like giving up",
          "This maybe the night that my dreams might let me know",
          "Designer clothes, fashion shows",
          "You must think that I'm new to this",
          "Give me a run for my money",
          "This is America",
          "I am what I am",
          "This is perfect",
          "Let's find out and see",
          "Why am I yelling?",
          "That's really all",
          "I don't even understand",
          "Can we talk for a moment?",
          "I wanna get married",
          "All for you",
          "I go insane",
          "Nobody else can relate",
          "You had it then you lost it",
          "The tables have turned",
          "How long has this been goin' on?",
          "Heaven only knows where you've been",
          "While we're young",
          "The feeling won't let me sleep",
          "Will the stars align?",
          "Make it easy",
          "Come on now, follow my lead",
          "Livin' too fast",
          "One night'll change your whole life",
          "I was only 8 years old watching Nick at Nite",
          "Just enjoy the moment"
          "I can see it all right now",
          "We can do anything if we put our minds to it",
          "You gave me comfort",
          "Not your reason, not your future",
          "I want to change my mind",
          "I'll come back",
          "We used to live on Instagram",
          "Wait a minute",
          "I'm just trying to shed a little light",
          "Everybody says say something",
          "This is real life",
          "We've got a long, long way to go",
          "Look good in the moonlight",
          "Am I lucky or not?",
          "We are clear",
          "Face every problem",
          "It's too good to be true",
          "It's powerful",
          "I can't stand it",
          "If you made up your mind, then make it",
          "You just might be doing whatever it takes to drown out the noise",
          "Speak up",
          "Your time is up",
          "But we never stop",
          "Send a prayer to the ones up above"
         ]

#Lyrics from the top 100 songs of 1996
topninetysix = ["Come and find me",
              "Sorry I never told you",
              "You were my voice when I couldn't speak",
              "Nobody knows it but me",
              "I will not stand in your way",
              "I'll turn right back around",
              "That's how we roll",
              "Feels like I'm standing in a timeless dream",
              "I can touch the sky",
              "You got me twisted",
              "I think I can",
              "You always were two steps ahead, of everyone",
              "It's like rain on your wedding day",
              "For every win, someone must fail",
              "I know we're headed somewhere",
              "I have but one concern",
              "How do you feel?",
              "It's all coming back to me",
              "If I could reach the stars",
              "For as long as I can remember",
              "Are you for sure?",
              "I'm one of the chosen few",
              "I know everything",
              "I still can't turn away",
              "They say they're better than you and you agree",
              "They don't like the game we play",
              "It was so, so crazy of me",
              "Am I very far now?",
              "I thought you should know",
              "Nobody callin' on the phone",
              "They say I must be one of the wonders",
              "Eleven years of sacrifice",
              "Too much television watchin' got me chasin' dreams",
              "I thought I told you that we won't stop",
              "Keep it on the down low",
              "So what's my chance",
              "I travel the world",
              "With the memories that can't be erased",
              "I guess I was wrong",
              "Help I need somebody",
              "Are we listening?",
              "Please excuse, if I come across rude",
              "I don't know where to start",
              "Faster than the speed of sound",
              "I still feel the same",
              "Oh my whole life has been much better than ever before",
              "My whole world changes",
              "Count on me through thick and thin",
              "I'm in heaven",
              "Can you teach me about tomorrow",
              "You'll see",
              "I almost cried 'cause it was so beautiful",
              "We'll be famous on TV",
              "I could not see all the beauty and wonder wrapping around me",
              "It's kinda funny",
              "Today is gonna be the day",
              "Don't ever disrespect",
              "But to my great surprise",
              "Rolling down the strip",
              "There is something amiss",
              "Press rewind",
              "I made my way into the night",
              "Hold on tight and don't let go",
              "Tonight's the night",
              "Children know, understand, and believe, that there will be more and more, love and peace, for eternity, love and peace, for everybody",
              "This tape will self-destruct in 5 seconds",
              "Everbody wants to live like they want to live",
              "'Cause I'm just a girl",
              "She wouldn't have to worry",
              "I want them to know",
              "I saw you first",
              "Just once if I have the chance",
              "Don't be afraid",
              "And I wonder who will walk with me when I get there",
              "It can't be that bad",
              "This I pray",
              "I can rock a party like nobody",
              "Just by mistake",
              "To hell with the consequence",
              "Now I know",
              "Don't leave me out in the rain",
              "Dancing free until the morning light",
              "You remind me of something",
              "I've seen the world, been to many places",
              "It will never end",
              "Let's make a date",
              "It's all up to you",
              "You've got all I need",
              "Push me to the limit",
              "No complications just attitude",
              "Never miss what you never had",
              "And the fear still shakes me",
              "Now I see why don't nobody leave",
              "You can do what you want just seize the day",
              "Got a fist of pure emotion",
              "I fight back in my mind",
              "Would you feel better?",
              "Couldn't stand him",
              "Sometimes you're crazy and you wonder why",
              "Don't be so hard on yourself"
             ]

#Lyrics of popular songs from numerous decades and genres
ofalltime = ["Well, I’ve been afraid of changing",
            "Cause I’ve built my life around you",
            "But time makes you bolder",
            "Even children get older",
            "And I’m getting older too",
            "I decided long ago, never to walk in anyone’s shadows",
            "If I fail, if I succeed",
            "At least I’ll live as I believe",
            "No matter what they take from me",
            "They can’t take away my dignity"
            "Some will win, some will lose",
            "Some were born to sing the blues",
            "The movie never ends",
            "It goes on and on and on and on",
            "If I leave here tomorrow, would you still remember me?",
            "If we weren't all crazy we would go insane",
            "Take my hand, take my whole life too",
            "All it'd take is one flight, we'd be in the same time zone",
            "Had to have high, high hopes for a living, shooting for the stars when I couldn't make a killing",
            "Just a small town girl, living in a lonely world",
            "What I want you've got, it might be hard to handle",
            "Something takes a part of me",
            "At first I was afriad, I was petrified",
            "So do you think you can tell heaven from hell",
            "Can I make it any more obvious?",
            "Making my way downtown, walking fast, faces pass and I'm homebound",
            "I get knocked down, but I get up again",
            "Nice to meet you",
            "Look at the stars, look how they shine for you, and everything you do",
            "I remember when I lost my mind, there was something so pleasant about that place",
            "And we danced all night to the best song ever",
            "Written in these walls are the stories that I can't explain",
            "There are two paths you can go by",
            "There's still time to change the road you're on",
            "How long it's been since yesterday, what about tomorrow",
            "But always somehow I made it, I made it through",
            "None but ourselves can free our minds",
            "Don't criticize what you can't understand",
            "You may say that I'm a dreamer",
            "You have every right to a beautiful life",
            "I'd trade all my tomorrows for one single yesterday",
            "Wish I could say Thank You",
            "The more money we come across, the more problems we see",
            "Love is not a victory march, it's a cold and it's a broken hallelujah",
            "If you want to make the world a better place, take a look at yourself and make a change",
            "Don't carry the world upon your shoulders",
            "Express yourself",
            "Shyness can stop you from doing all the things in life you'd like to",
            "Thunder only happens when it's raining",
            "Don't put your life in the hands of a rock'n'roll band",
            "There's still time to change the road you're on",
            "And so, become yourself, because the past is just a good bye",
            "This might be the only opportunity I got",
            "Work it harder, make it better, do it faster...that that don't kill me will only make me stronger",
            "It's better to burn out than to fade away",
            "You can't always get what you want",
            "All that money you made will never buy back your soul",
            "Everything is everything",
            "We're just a million",
            "Don't fear",
            "Everybody sees...everybody feels",
            "If you try the best you can, the best you can is good enough",
            "What's the point in being rich?",
            "You gotta fight for your right",
            "We can be heroes",
            "Just for one day",
            "Even though you're fed up, you gotta keep your head up",
            "Either you play the game or watch the game play you",
            "Darling I'm a nightmare",
            "I'm gonna live like tomorrow doesn't exist",
            "Find me where the wild things are",
            "If I was you, I'd want to be me too",
            "Eye to eye, so alive",
            "Here for infinity",
            "Feels so good being bad",
            "I came fluttering in from Neverland",
            "More than just survival. This is my revival.",
            "I'm no beauty queen, I'm just beautiful me",
            "Who's gonna walk you through the dark side of the morning?",
            "There's nothing I can do",
            "I should've walked away",
            "On a wire between will and what will be",
            "No matter what your friends might say",
            "And I'm not happy and I'm not sad",
            "Oh please save your life, because you only have one",
            "They'll tell your secrets to a friend",
            "I'm ready to grow young again",
            "I'm odds and ends, but I'll be stumbling away",
            "I've done alright up to now",
            "What will it be?",
            "Welcome to your life",
            "I'll still know you",
            "Livin' on a prayer",
            "I'll do all that I can",
            "Same as it ever was",
            "All night long",
            "Should I stay or should I go?",
            "At this moment",
            "Let me out",
            "That's all they really want"
           ]
print("Singing Through the Years by Elizabeth Finto")
for l in range(100):
    print(random.choice(billboardtop))
    print(random.choice(topninetysix))
    print(random.choice(ofalltime))
